language: 
  - generic

os:
  - linux

install:
  - sudo apt-get update;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
  - bash miniconda3.sh -b -p $HOME/miniconda3

  # CONDA PY3 BUILD
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - which python
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install pip notebook nbconvert -qy

  # install ipyrad from MASTER using pip local
  - git clone https://github.com/dereneaton/ipyrad.git ipyrad-git
  - cd ipyrad-git
  - pip install -e .
  - cd ..

# command to run tests
script: 
 
  #test installation
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - python -c "import toyplot; print(ipyrad.__version__)"

  # test sim data assembly
  # - jupyter-nbconvert --ExecutePreprocessor.kernel_name="python3" --execute docs/4-tutorial.ipynb --to html
  