sudo: true
language: python
python:
    - "2.7"
install:
    - env | sort
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels ipyrad
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION mock numpy pip
    - source activate test-environment
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        conda install ipyrad
      fi
script:
    - coverage run --source ipyrad --omit ipyrad/testing.py -m nose --exclude-dir ipyrad
    - coverage run --append --source ipyrad --omit ipyrad/testing.py -m behave
    - coverage report
    - python backend-report.py
after_script:
    - coveralls