name: ipyrad
channels:
- ipyrad
dependencies:
- python=2.7
- pip>=9.0
- cython
- ipython>=5.0
- ipyparallel>=6.0.2
- numpy>1.9
- scipy>0.10
- pandas>=0.19
- h5py
- mpi4py
- sphinx>1.2
- numba>=0.31
- llvmlite>=0.16
- dask

#- jupyter