# This file created by conda-build v2.0.1-fix-output+skip+61.g6003670
# meta.yaml template originally from:
# /bioconda-recipes/recipes/htslib, last modified Tue Oct 25 11:42:35 2016
# ------------------------------------------------

package:
    name: htslib
    version: 1.3.1
source:
    fn: htslib-1.3.1.tar.bz2
    md5: 16d78f90b72f29971b042e8da8be6843
    url: https://github.com/samtools/htslib/releases/download/1.3.1/htslib-1.3.1.tar.bz2
build:
    number: '1'
    skip: 'False'
requirements:
    build:
        - curl
    run:
        - curl
about:
    home: https://github.com/samtools/htslib
    license: MIT
    summary: C library for high-throughput sequencing data formats.


