# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /opt/recipe, last modified Mon May  8 18:30:27 2017
# ------------------------------------------------

package:
    name: htslib
    version: 1.4.1
source:
    fn: htslib-1.4.1.tar.bz2
    md5: e549fee04d95c1cf8f46347e9e9bbd93
    url: https://github.com/samtools/htslib/releases/download/1.4.1/htslib-1.4.1.tar.bz2
build:
    number: '0'
requirements:
    build:
        - curl
        - bzip2
        - xz
    run:
        - curl
        - bzip2
        - xz
about:
    home: https://github.com/samtools/htslib
    license: MIT
    summary: C library for high-throughput sequencing data formats.
