# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Mar 22 09:31:26 2017
# ------------------------------------------------

package:
    name: pysam
    version: 0.10.0
source:
    fn: pysam-0.10.0.tar.gz
    md5: a1f3333ce60f8de542624cb07c792fc0
    url: https://pypi.python.org/packages/87/8e/d2d8238558970df37c7aa01ddec63057a98042334e939b4c1c69cb9a2504/pysam-0.10.0.tar.gz
build:
    binary_relocation: 'False'
    number: '3'
    skip: 'False'
requirements:
    build:
        - gcc
        - cython
        - python
        - setuptools
        - zlib
        - curl
        - htslib >=1.3,<1.4
        - samtools >=1.3,<1.4
        - bcftools >=1.3,<1.4
    run:
        - libgcc
        - python
        - zlib
        - curl
        - htslib >=1.3,<1.4
        - samtools >=1.3,<1.4
        - bcftools >=1.3,<1.4
test:
    imports:
        - pysam
about:
    home: https://github.com/pysam-developers/pysam
    license: MIT
    summary: Pysam is a python module for reading and manipulating Samfiles. It is
        a lightweight wrapper of the samtools C-API. Pysam also includes an interface
        for tabix.


