package:
  name: bucky
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: http://www.stat.wisc.edu/~ane/bucky.git

build:
  number: '0'
  script: build.sh
  skip: 'False'

about:
  home: 
  license: MIT
