package:
  name: ipyrad
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/dereneaton/ipyrad.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true

requirements:
  build:
    - python {{PY_VER}}*,>=2.7
    - setuptools
    - cython
    - h5py
    - ipyparallel >=6.0.2
    - ipython >=5.0.0
    - jupyter_client
    - jupyter
    - notebook >=5.0
    - mpi4py
    - nbconvert
    - numba >=0.33
    - numpy >=1.7
    - pandas >=0.16
    - scipy >=0.16
    - sphinx
    - networkx
    - cutadapt >=1.12
    - dask
    - pysam >=0.10.0     

  run:
    - ipython >=5.0.0
    - ipyparallel >=6.0.2
    - cython
    - scipy >=0.16
    - h5py
    - nbconvert
    - numba >=0.33
    - jupyter_client
    - jupyter
    - notebook >=5.0
    - sphinx
    - pandas
    - mpi4py
    - numpy >=1.7
    - networkx
    - dask
    - cutadapt >=1.12
    - pysam >=0.10.0
    - setuptools >=28.0.0

  commands:
    - ipyrad -h

about:
  home: http://github.com/dereneaton/ipyrad
  license: GPLv3
  summary: Interactive assembly and analysis of RAD-seq data sets.
