package:
  name: ipyrad
  version: {{ GIT_DESCRIBE_TAG }}
  # version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/dereneaton/ipyrad.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true
  script: python setup.py install

requirements:
  build:
    - python {{ python }}
    - setuptools >=28.0.0
    - jupyter
    - ipython >=5.0.0
    - ipyparallel >=6.0.2
    - numpy >=1.7
    - scipy >=0.16
    - numba >=0.33
    - pandas >=0.16
    - h5py
    - mpi4py
    - pigz
    - future
    # - cutadapt >=1.12
    # - pysam >=0.10.0     
    # - toytree

  run:
    - python {{ python }}
    - setuptools >=28.0.0
    - jupyter
    - ipython >=5.0.0
    - ipyparallel >=6.0.2
    - numpy >=1.7
    - scipy >=0.16
    - numba >=0.33
    - pandas >=0.16
    - h5py
    - mpi4py
    - pigz
    - future
    # - cutadapt >=1.12
    # - pysam >=0.10.0     
    # - toytree

  commands:
    imports:
      - ipyrad
    - ipyrad -h

about:
  home: http://github.com/dereneaton/ipyrad
  license: GPLv3
  summary: Interactive assembly and analysis of RAD-seq data sets.
