
{% set name = "ipyrad" %}
{% set version = "0.9.1" %}


package:
  name: {{name}}
  version: {{version}}
  # {{ GIT_DESCRIBE_TAG }}
  # version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/dereneaton/{{name}}.git
  git_tag: hotfix
  #fn: ipyrad-0.7.30.tar.gz
  #url: https://github.com/dereneaton/ipyrad/archive/0.7.30.tar.gz
  #sha256: d4f40c723ac4cbd1a39ad217456bc1e66a8f836523c52ec5d3bb7e8cd2c7f205
  # git_url: https://github.com/dereneaton/ipyrad.git

build:
  number: 0
  # noarch: python
  # binary_relocation: true
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
    - pandas
    - scipy
    - numba >=0.37
    - future
    - h5py
    - ipyparallel >=6.0.2
    - pysam
    - mpi4py    
    - requests
    - cutadapt
  run:
    - python
    - pandas
    - scipy
    - numba >=0.37
    - future
    - h5py
    - ipyparallel >=6.0.2
    - cutadapt
    - pysam
    - mpi4py
    - requests

test:
  imports:
    - ipyrad
  commands:
    - ipyrad -h

about:
  home: http://github.com/dereneaton/ipyrad
  license: GPL3
  license_file: LICENSE.txt
  summary: Interactive assembly and analysis of RAD-seq data sets.
