package:
    name: cutadapt
    version: '1.12'
source:
    fn: cutadapt-1.12.tar.gz
    md5: 27039acb5ae6259f82abfcff186bee7a
    url: https://pypi.python.org/packages/41/9e/5b673f766dcf2dd787e0e6c9f08c4eea6f344ea8fce824241db93cc2175f/cutadapt-1.12.tar.gz#md5=27039acb5ae6259f82abfcff186bee7a
build:
    number: '0'
    skip: 'False'
requirements:
    build:
        - python
        - xopen
    run:
        - python
        - xopen
test:
    commands:
        - cutadapt --version > /dev/null
    imports:
        - cutadapt
        - cutadapt.scripts
about:
    home: https://cutadapt.readthedocs.io/
    license: MIT License
    summary: trim adapters from high-throughput sequencing reads


