package:
  name: clumpp
  version: !!str 1.1.2

source:
  fn: CLUMPP_Linux64.1.1.2.tar.gz
  url: https://web.stanford.edu/group/rosenberglab/software/CLUMPP_Linux64.1.1.2.tar.gz # [linux]
  md5: ae0ba74fc56a2103173b77f5ed4519da                                                 # [linux]
  url: https://web.stanford.edu/group/rosenberglab/software/CLUMPP_MacOSX.1.1.2.tar.gz  # [osx]
  md5: bf044d7ce2b807b5ceec937bb2a764fd                                                 # [osx]

build:
  number: '0'
  skip: 'False'

about:
  home: https://web.stanford.edu/group/rosenberglab/software/
  license: MIT
