name: ipyrad
channels: 
  - conda-forge
  - bioconda
  - ipyrad
  - eaton-lab
dependencies:
  - ipyrad
  - ipcoal
  - toytree
  - raxml
  - mrbayes
  - structure
  - clumpp
  - tetrad 
  - scikit-learn 
  - bcftools
  - htslib
  - bpp
  - bucky
  - treemix   # forces openblas on numpy/scipy
