package:
  name: ipyrad
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/dereneaton/ipyrad.git

build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cython
    - dill
    - h5py
    - ipyparallel
    - ipython ==4.0.0
    - jupyter
    - mpi4py
    - nbconvert
    - numba
    - numpy >=1.7
    - pandas
    - psutil
    - scipy
    - sphinx
    - python {{PY_VER}}*,>=2.7
  run:
    - ipython ==4.0.0
    - ipyparallel
    - cython
    - scipy 
    - h5py
    - numba
    - jupyter
    - sphinx
    - dill
    - pandas
    - mpi4py
    - psutil
    - numpy >=1.7


about:
  home: http://github.com/dereneaton/ipyrad
  license: GPLv3
  summary: Interactive assembly and analysis of RAD-seq data sets.
