package:
  name: ipyrad
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/dereneaton/ipyrad.git

build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cython
    - h5py
    - ipyparallel >=5.1.0
    - ipython >=4.0.0
    - jupyter_client
    - jupyter
    - mpi4py
    - nbconvert
    - numba >=0.28
    - numpy >=1.7
    - pandas >=0.16
    - scipy >=0.16
    - sphinx
    - python {{PY_VER}}*,>=2.7
  run:
    - ipython >=4.0.0
    - ipyparallel >=5.1.0
    - cython
    - scipy >=0.16
    - h5py
    - nbconvert
    - numba >=0.28
    - jupyter_client
    - jupyter
    - sphinx
    - pandas
    - mpi4py
    - numpy >=1.7


about:
  home: http://github.com/dereneaton/ipyrad
  license: GPLv3
  summary: Interactive assembly and analysis of RAD-seq data sets.
