package:
  name: ipyrad
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: https://github.com/dereneaton/ipyrad.git

build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - ipython ==4.0.0
    - ipyparallel
    - cython
    - scipy 
    - numpy >=1.7
    - h5py
    - jupyter
    - sphinx
    - dill
    - pandas
  run:
    - numpy >=1.7


about:
  home: http://github.com/dereneaton/ipyrad
  license: GPLv3
  summary: Interactive assembly and analysis of RAD-seq data sets.
