package:
  name: structure
  version: !!str 2.3.4

source:
  fn: structure_kernel_source.tar.gz
  url: http://web.stanford.edu/group/pritchardlab/structure_software/release_versions/v2.3.4/structure_kernel_source.tar.gz
  md5: 4e0591678cdbfe79347d272b5dceeda1

build:
  number: '0'
  skip: 'False'

about:
  home: http://pritchardlab.stanford.edu/structure_software/
  license: MIT
